Bible-Verse-App/Bible-Verse-App/Models/BibleVerse.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bible_Verse_App.Models
{
    public class BibleVerse
    {

        [Required]
        [DisplayName("Testament")]
        [StringLength(50, ErrorMessage ="Testament muct be between 1 and 50 characters")]
        public string Testament { get; set; }

        [Required]
        [DisplayName("Book")]
        [StringLength(50, ErrorMessage = "Testament muct be between 1 and 50 characters")]
        public string Book { get; set; }

        [Required]
        [DisplayName("Chapter Number")]
        [Range(1, 10000, ErrorMessage = "Must be between 1 and 10,000")]
        public int ChapterNumber { get; set; }

        [Required]
        [DisplayName("Verse Number")]
        [Range(1, 10000, ErrorMessage = "Must be between 1 and 10,000")]
        public int VerseNumber { get; set; }

        [Required]
        [DisplayName("Verse Text")]
        public string VerseText { get; set; }

        public BibleVerse()
        {
        }

        public BibleVerse(string testament, string book, int chapterNumber, int verseNumber, string verseTest)
        {
            Testament = testament;
            Book = book;
            ChapterNumber = chapterNumber;
            VerseNumber = verseNumber;
            VerseText = verseTest;
        }
    }
}

Bible-Verse-App/Bible-Verse-App/Controllers/BibleVerseController.cs
/*
 * Benchmark Bible Project 
 * ver. 1 
 * Brydon Johnson
 * 
 * Controller: BibleVerseController:
 *      this controller handles all actions pertaining to the Bible Verse functionality
 *      
 *      Functions:
 *          Index()
 *              returns "AddBibleVerse" view
 *          GoToSearch()
 *              navigates to "SearchForBibleVerse" view
 *          AddBibleVerse(BibleVerse bibleVerse)
 *              uses the BibleVerseService object to add the user input bible verse to the dbo.verses database table
 *          SearchForBibleVerse(BibleVerse queryVerse)
 *              uses the BibleVerseService object to query the user input bible verse from the dbo.verses database table
 *              
 */





using Bible_Verse_App.Models;
using Bible_Verse_App.Services.Business;
using Bible_Verse_App.Services.Utility;
using NLog;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bible_Verse_App.Controllers
{
    public class BibleVerseController : Controller
    {



        // returns AddBibleVerse view
        public ActionResult Index()
        {
            return View("AddBibleVerse");
        }

        // returns SearchForBibleVerse view
        public ActionResult GoToSearch()
        {
            return View("SearchForBibleVerse");
        }

        public ActionResult AddBibleVerse(BibleVerse bibleVerse)
        {
            BibleVerseService bibleVerseService = new BibleVerseService();
            if (bibleVerseService.AddBibleVerse(bibleVerse))
            {
                MyLogger.GetInstance().Info("Added Bible Verse to the database");
                return View("VerseSuccessfullyAdded", bibleVerse);
            }
            else
            {
                MyLogger.GetInstance().Error("Failed to add Bible Verse to database");
                return View("AddFailed");
            }
        }

        public ActionResult SearchForBibleVerse(BibleVerse queryVerse)
        {
            BibleVerseService bibleVerseService = new BibleVerseService();

            BibleVerse bibleVerse = bibleVerseService.SearchForBibleVerse(queryVerse);

            if (bibleVerse.Testament!= null)
            {
                MyLogger.GetInstance().Info("Located Bible Verse with search");
                return View("DisplayBibleVerse", bibleVerse);
            }
            else
            {
                MyLogger.GetInstance().Info("Failed to Locate the Bible Verse with search");
                return View("NoResultsFound");
            }
        }
    }
}

Bible-Verse-App/Bible-Verse-App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bible_Verse_App.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Bible-Verse-App/Bible-Verse-App/Views/BibleVerse/AddBibleVerse.cshtml
@model Bible_Verse_App.Models.BibleVerse

@{
    ViewBag.Title = "AddBibleVerse";
}

<h2>AddBibleVerse</h2>



@using (Html.BeginForm("AddBibleVerse", "BibleVerse", FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Testament, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChapterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bible-Verse-App/Bible-Verse-App/Views/BibleVerse/AddFailed.cshtml
@{
    ViewBag.Title = "AddFailed";
}

<h2>Verse Addition Failed</h2>

Bible-Verse-App/Bible-Verse-App/Views/BibleVerse/DisplayBibleVerse.cshtml
@model Bible_Verse_App.Models.BibleVerse

@{
    ViewBag.Title = "DisplayBibleVerse";
}

<h2>Bible Verse Found!</h2>

<div>
    <h4>BibleVerse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Testament)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Testament)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Book)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChapterNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseText)
        </dd>

    </dl>
</div>

Bible-Verse-App/Bible-Verse-App/Views/BibleVerse/SearchForBibleVerse.cshtml
@model Bible_Verse_App.Models.BibleVerse

@{
    ViewBag.Title = "SearchForBibleVerse";
}

<h2>SearchForBibleVerse</h2>

@using (Html.BeginForm("SearchForBibleVerse", "BibleVerse", FormMethod.Get)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BibleVerse</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Testament, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Testament, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Testament, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Book, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Book, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Book, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChapterNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ChapterNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ChapterNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VerseNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VerseNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VerseNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Bible-Verse-App/Bible-Verse-App/Views/BibleVerse/VerseSuccessfullyAdded.cshtml
@model Bible_Verse_App.Models.BibleVerse

@{
    ViewBag.Title = "VerseSuccessfullyAdded";
}

<h2>VerseSuccessfullyAdded</h2>

<div>
    <h4>BibleVerse</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Testament)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Testament)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Book)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Book)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ChapterNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ChapterNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VerseText)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VerseText)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bible-Verse-App/Bible-Verse-App/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Bible Benchmark</h1>
    <p class="lead">Welcome to the best place on the internet for just adding and viewing bible verses</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            Click below to add a bible verse
        </p>
        @Html.ActionLink("Add Verse", "Index", "BibleVerse", null,  new { @class = "btn btn-primary" })
    </div>
    <div class="col-md-4">
        <h2>View Your Verses</h2>
        <p>OR Click this button in order to search through the Bible Verses you have already added</p>
        @Html.ActionLink("Search Verses", "GoToSearch", "BibleVerse", null, new { @class = "btn btn-primary" })
    </div>
    
</div>

Bible-Verse-App/Bible-Verse-App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Bible Benshmark", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Add Verse", "Index", "BibleVerse")</li>
                    <li>@Html.ActionLink("Search", "GoToSearch", "BibleVerse")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>